apiVersion: v1
kind: ConfigMap
metadata:
  name: angryduck-config
  namespace: angryduck
data:
  CONTROLLER_LISTEN_ADDR: ":8080"
  WORKER_STALE_AFTER_S: "30"
  TARGET_TTL_S: "120"
  RANK_INTERVAL_S: "10"
  RANK_TOP_N: "2"

  WORKER_LISTEN_ADDR: ":18081"
  NODE_EXPORTER_URL: "http://localhost:9100/metrics"
  CONTROLLER_URL: "http://angryduck-controller.angryduck.svc.cluster.local:8080"
  REPORT_INTERVAL_S: "15"
  GC_CHECK_INTERVAL_S: "60"
  GC_MISS_THRESHOLD: "5"
  GC_GRACE_PERIOD_S: "60"
  CONTAINER_RUNTIME: "containerd"
