apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: angryduck-controller
  labels:
    app.kubernetes.io/name: angryduck
    app.kubernetes.io/component: controller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "watch"]
