apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: angryduck-worker
  namespace: angryduck
  labels:
    app.kubernetes.io/env: stg
    app.kubernetes.io/name: angryduck
    app.kubernetes.io/component: worker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: angryduck-worker
subjects:
  - kind: ServiceAccount
    name: angryduck-worker
    namespace: angryduck
