apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: angryduck-worker
  namespace: angryduck
  labels:
    app.kubernetes.io/env: stg
    app.kubernetes.io/name: angryduck
    app.kubernetes.io/component: worker
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    resourceNames: ["angryduck-worker"]
    verbs: ["get"]
