apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: angryduck-controller
  namespace: angryduck
  labels:
    release: prometheus
    app.kubernetes.io/env: stg
    app.kubernetes.io/name: angryduck
    app.kubernetes.io/component: controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/env: stg
      app.kubernetes.io/name: angryduck
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - angryduck
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
