FROM golang:1.27.0-alpine3.24 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY internal ./internal
COPY cmd/controller ./cmd/controller
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/angryduck-controller ./cmd/controller

FROM gcr.io/distroless/static-debian13
COPY --from=build /out/angryduck-controller /angryduck-controller
ENTRYPOINT ["/angryduck-controller"]
