apiVersion: v1
kind: Secret
metadata:
  name: angryduck-mirror
  namespace: angryduck
  labels:
    app.kubernetes.io/env: mgmt
    app.kubernetes.io/name: angryduck
    app.kubernetes.io/component: worker
type: Opaque
data:
  token: NDRmNjY4ODI1ZDBmYTZjYmVmMThiYmIxNjVjYzEwNDQ1NGRmMTA4M2RlZGIwYWU4YjgwNTIwOWY3OWU0OTkxMA==
