{{- if not .Values.sharedToken.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "angryduck.sharedTokenSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "angryduck.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ include "angryduck.token" (dict "namespace" .Release.Namespace "name" (include "angryduck.sharedTokenSecret" .)) }}
{{- end }}
{{- if and .Values.webhookToken.enabled (not .Values.webhookToken.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "angryduck.webhookTokenSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "angryduck.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ include "angryduck.token" (dict "namespace" .Release.Namespace "name" (include "angryduck.webhookTokenSecret" .)) }}
{{- end }}
{{- if and .Values.registryCredentials.dockerconfigjson (not .Values.registryCredentials.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "angryduck.registryCredentialsSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "angryduck.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registryCredentials.dockerconfigjson | b64enc }}
{{- end }}
