{{- if .Values.serviceMonitor.enabled }}
{{- range $component := list "controller" "worker" }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "angryduck.fullname" $ }}-{{ $component }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "angryduck.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
    {{- with $.Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "angryduck.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $.Values.serviceMonitor.interval }}
{{- end }}
{{- end }}
